---
title: "Spectral shape descriptors"
author: "Rafael Maia, Thomas White, Hugo Gruson, Pierre-Paul Bitton, Chad Eliason"
date: "`r Sys.Date()`"
output: html_document
bibliography: table_montgomerie.bib
csl: open-biology.csl
---

<style>
tr:hover {
  background-color: #eee;
}
</style>

This table is adapted from @Montgomerie2006 and lists all spectral descriptors
that are computed by the `summary` function in `pavo`.

| Color variable | Names used | Formula | Reference |
|:---------------|:-----------|:-------:|:---------:|
| Brightness     | Total brightness, total reflectance, spectral intensity | $$B_1=B_T=\int_{\lambda_{min}}^{\lambda_{max}} R_i = \sum_{\lambda_{min}}^{\lambda_{max}} R_i$$ | @Andersson1999,@Andersson2002,@Ornborg2002,@Andersson1998,@Smiseth2001,@Saks2003,@Pryke2001,@Shawkey2003 |
| | Mean brightness | $$B_2=\frac{\sum_{\lambda_{min}}^{\lambda_{max}} R_i}{n_w}=\frac{B_1}{n_w}$$ | @Delhey2003,@Siefferman2005 |
| | Intensity | $$B_3=R_{max}$$ | @Andersson1999,@Keyser2000,@Keyser1999 |
| Saturation | Chroma, reflectance ratio, spectral purity | $$S_1= \frac{\sum_{\lambda_a}^{\lambda_b} R_i}{\sum_{\lambda_{min}}^{\lambda_{max}} R_i} = \frac{\sum_{\lambda_a}^{\lambda_b} R_i}{B_1}$$ | @Ornborg2002,@Andersson1998,@Smiseth2001,@Siefferman2005,@Peters2004,@Shawkey2003 | 
| | Spectral saturation | $$S_2 = \frac{R_{max}}{R_{min}}$$ | @Andersson1999 |
| | Chroma | $$S_3 = \frac{\sum_{\lambda_{R_{max}}-50}^{\lambda_{R_{max}}+50} R_i}{B_1}$$ | @Shawkey2003 |
| | Spectral purity | $$S_4 = \lvert b\text{max}_{neg}\lvert$$ | @Andersson1999 |
| | Chroma | $$S_5=\sqrt{(B_r-B_g)^2+(B_y-B_b)^2}$$ | @Saks2003 |
| | Constrast, amplitude | $$S_6 = R_{max} - R_{min}$$ | @Keyser2000,@Keyser1999 |
| | Spectral saturation | $$S_7 = \frac{\left(\sum_{\lambda_{320}}^{\lambda_{R_{mid}}} R_i - \sum_{\lambda_{R_{mid}}}^{\lambda_{700}} R_i\right)}{B_1}$$ | @Andersson2002,@Pryke2001 |
| | Chroma | $$S_8=\frac{R_{max}-R_{min}}{B_2}$$ | @Andersson2002,@Smiseth2001 |
| | Carotenoid chroma | $$S_9=\frac{R_{\lambda_{700}}-R_{\lambda_{450}}}{R_{\lambda_{700}}}$$ | @Peters2004 |
| | Peaky chroma | $$S_{10}=\lvert b\text{max}_{neg} \lvert\frac{R_{max}-R_{min}}{B_2}$$ | @Ornborg2002 | 
| Hue | Hue, peak wavelength, spectral location | $$H_1=\lambda_{R_{max}}$$ | @Andersson1999,@Ornborg2002,@Andersson1998,@Delhey2003,@Smiseth2001,@Keyser2000,@Siefferman2005,@Shawkey2003 |
| | Hue | $$H_2 = \lambda_{b\text{max}_{neg}}$$ | @Andersson1998,@Smiseth2001 |
| | Hue | $$H_3 = \lambda_{R_{mid}}$$ | @Andersson2002,@Smiseth2001,@Pryke2001 |
| | Hue | $$H_4 = \arctan\left(\frac{B_y-B_b}{B_r-B_g}\right)$$ | @Saks2003 |
| | Hue | $$H_5 = \lambda_{b\text{max}_{pos}}$$ | @Keyser1999 |

- $R_i$: percentage (or proportional) reflectance at the $i$th wavelength
- $\lambda_{max}$, $\lambda_{min}$: upper and lower (respectively) limits of
wavelengths
- $n_w$: number of wavelength intervals used to calculate $B_T$
- $R_{max}$, $R_{min}$: maximum and minimum percent reflectances, respectively
- $\lambda_{R_{max}}$: wavelength at maximum reflectance
- $b\text{max}_{neg}$, $b\text{max}_{pos}$: maximum negative and positive slopes
of reflectance curve in a region of interest
- $B_r$, $B_y$, $B_g$, $B_b$: total brightness in red ($r=625-700\,nm$), yellow
($y=550-625\,nm$), green ($g=475-550\,nm$) and blue ($b=400-475\,nm$) segments
of the spectrum
- $\lambda_{R_{mid}}$: wavelength at the reflectance midpoint between $R_{max}$
and $R_{min}$ (i.e., $\frac{R_{max}+R_{min}}{2}$)

# References
